/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#faf9fd',
        'surface-dim': '#dad9dd',
        'surface-bright': '#faf9fd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f7',
        'surface-container': '#efedf1',
        'surface-container-high': '#e9e7eb',
        'surface-container-highest': '#e3e2e6',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#43474e',
        'inverse-surface': '#2f3033',
        'inverse-on-surface': '#f1f0f4',
        'outline': '#74777f',
        'outline-variant': '#c4c6cf',
        'surface-tint': '#455f88',
        'primary': '#002045',
        'on-primary': '#ffffff',
        'primary-container': '#1a365d',
        'on-primary-container': '#86a0cd',
        'inverse-primary': '#adc7f7',
        'secondary': '#555f71',
        'on-secondary': '#ffffff',
        'secondary-container': '#d6e0f6',
        'on-secondary-container': '#596376',
        'tertiary': '#321b00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4f2e00',
        'on-tertiary-container': '#c6955e',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#adc7f7',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#2d476f',
        'secondary-fixed': '#d9e3f9',
        'secondary-fixed-dim': '#bdc7dc',
        'on-secondary-fixed': '#121c2c',
        'on-secondary-fixed-variant': '#3d4759',
        'tertiary-fixed': '#ffddba',
        'tertiary-fixed-dim': '#f2bc82',
        'on-tertiary-fixed': '#2b1700',
        'on-tertiary-fixed-variant': '#633f0f',
        'background': '#faf9fd',
        'on-background': '#1a1c1e',
        'surface-variant': '#e3e2e6',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'base': '8px',
        'xs': '4px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '16px',
        'container-max': '1200px',
      },
      fontFamily: {
        sans: ['Manrope', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
      },
      boxShadow: {
        'card': '0 4px 6px -1px rgba(26, 54, 93, 0.05), 0 2px 4px -1px rgba(26, 54, 93, 0.03)',
        'float': '0 10px 25px -5px rgba(26, 54, 93, 0.1), 0 8px 10px -6px rgba(26, 54, 93, 0.05)',
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [],
};
